// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtlvzkaitonogivggwtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0bHZ6a2FpdG9ub2dpdmdnd3RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NTc1NDEsImV4cCI6MjA2NjIzMzU0MX0.DM7TFpVvU9AMMiS5GPypoXf7f4Yn9FNnx_dgzOFJ8k0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);